# Creating lists (1-D & Matrix)and converting into numpy array. Checking their type.

# Why use Numpy array? Why not just a list?
1. There are lot's of reasons to use a Numpy array instead of a "standard" python list object. Our main reasons are:

2. Memory Efficiency of Numpy Array vs list

3. Easily expands to N-dimensional objects

4. Speed of calculations of numpy array

5. Broadcasting operations and functions with numpy

All the data science and machine learning libraries we use are built with Numpy

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [4]:
my_array = np.array(my_list)

In [5]:
my_array

array([1, 2, 3])

In [6]:
type(my_array)

numpy.ndarray

In [7]:
matrix_list = [[1,2,3],[4,5,6]]
print(type(matrix_list))
matrix_list

<class 'list'>


[[1, 2, 3], [4, 5, 6]]

In [8]:
matrix_array = np.array(matrix_list)
print(type(matrix_array))
matrix_array

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6]])

# Built in methods to create arrays: arange, zeros&ones, linspace, eye, random - rand,randn,randint,seed

# arange

arange : Return evenly spaced numbers over a specified interval. 
When using a non-integer step, such as 0.1, it is often better to use numpy.linspace.
arange(start, stop, step) Values are generated within the half-open interval [start, stop), with spacing between values given by step.

In [9]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

# zeros and ones
Generate arrays of zeros or ones.

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.ones((3,8),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

# linspace
Note that .linspace() includes the stop value. To obtain an array of common fractions, increase the number of items:

In [12]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [16]:
np.linspace(0,10,16,endpoint=False)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ,
       5.625, 6.25 , 6.875, 7.5  , 8.125, 8.75 , 9.375])

# eye : identity matrix
Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random : 
Numpy also has lots of ways to create random number arrays:

# np.random.rand : 
Creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1)

In [18]:
np.random.rand(5)

array([0.58494517, 0.94568949, 0.71498354, 0.53526771, 0.41257974])

In [19]:
np.random.rand(5,5)

array([[0.65150967, 0.30147543, 0.59792806, 0.67191292, 0.51564921],
       [0.98972549, 0.48537155, 0.28443003, 0.43639789, 0.86498564],
       [0.46914409, 0.79748648, 0.20258019, 0.52978473, 0.93119406],
       [0.11600269, 0.75893281, 0.22197834, 0.08304846, 0.4202695 ],
       [0.39307346, 0.84559237, 0.44305281, 0.76917366, 0.72288974]])

# np.random.randn : 
If positive int_like arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1. A single float randomly sampled from the distribution is returned if no argument is provided.

In [14]:
np.random.randn(1,4)

array([[ 2.33601456,  2.00246046, -1.4801211 ,  0.50605957]])

In [21]:
np.random.randn()

0.922273629050253

In [22]:
np.random.randn(6,3,3)

array([[[ 0.59064206, -0.98748577,  0.03061764],
        [-1.06873598, -1.25467612,  0.66395004],
        [-0.46498064,  0.93102855, -0.32880437]],

       [[-1.3503498 , -1.10591827, -1.11570969],
        [-0.91919008,  0.86483839,  1.24474585],
        [ 0.17656109, -1.26200886, -0.45898588]],

       [[-0.18394309,  0.3365521 , -0.78460765],
        [ 1.31229551,  0.07222223, -0.66232207],
        [-0.43405887,  0.31588586, -0.57235795]],

       [[ 0.23957197, -1.35201721, -1.52256549],
        [ 1.46279102,  0.66467158,  1.29803767],
        [ 0.54913779, -0.28316763,  2.02935592]],

       [[-1.46395378, -0.94565206,  1.73408999],
        [-1.02539234, -1.49436264,  0.67604534],
        [-0.84108483,  0.32233864,  1.05976287]],

       [[ 0.7676318 ,  0.81369313,  0.32783414],
        [-0.61174717, -1.07454378, -0.03833585],
        [-0.77903788,  1.01381365,  0.21915012]]])

# randint
Return random integers from low (inclusive) to high (exclusive).

In [15]:
np.random.randint(1,100,5)

array([79, 23, 35, 90, 69])

In [18]:
np.random.randint(1,100,size=10)

array([76, 29, 90, 41, 41, 17, 94, 43, 89, 57])

In [20]:
np.random.randint(1,100,size=(10,10))

array([[61, 85, 19, 31, 69, 36, 75, 17, 46, 53],
       [16, 51, 23, 75, 52,  4, 65,  1, 27, 34],
       [96, 35, 66, 74, 62, 89, 41, 40, 52, 40],
       [34, 37,  4, 15, 43, 89, 79, 69, 90, 84],
       [37, 58, 21,  7, 66, 45, 29, 70, 10, 16],
       [44, 98, 68,  4, 20, 34, 43, 48,  8, 47],
       [41, 41, 83, 75, 58, 17, 11, 41, 62, 47],
       [93, 54,  2, 34, 57, 27, 32, 40, 77, 74],
       [96, 44,  7, 76,  1, 73, 94, 81, 26, 28],
       [78,  3, 28, 40, 40,  3, 93, 97, 31, 63]])

In [25]:
np.random.randint([5,10,50],100) #upper and lower bounds can be defined.

array([11, 50, 92])

In [26]:
np.random.randint(1, [3, 5, 10])

array([2, 2, 3])

In [27]:
np.random.randint([1, 3, 5, 7], [[10], [20]]) #Generate a 2 by 4 array using broadcasting

array([[ 7,  4,  8,  8],
       [ 6,  4, 17, 11]])

# seed
Can be used to set the random state, so that the same "random" results can be reproduced

In [16]:
np.random.seed(42)
np.random.randn(10)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

In [19]:
np.random.seed(42)
np.random.randn(5)

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337])

# Reshape
Returns an array containing the same data with a new shape.

In [30]:
array_random = np.random.rand(3,4)
array_random

array([[0.15599452, 0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985, 0.83244264],
       [0.21233911, 0.18182497, 0.18340451, 0.30424224]])

In [31]:
array_random.reshape(4,3)

array([[0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449],
       [0.96990985, 0.83244264, 0.21233911],
       [0.18182497, 0.18340451, 0.30424224]])

In [32]:
np.reshape(array_random,(6,2))

array([[0.15599452, 0.05808361],
       [0.86617615, 0.60111501],
       [0.70807258, 0.02058449],
       [0.96990985, 0.83244264],
       [0.21233911, 0.18182497],
       [0.18340451, 0.30424224]])

# max, min, argmax, argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax 

In [33]:
arr=np.random.randint(1,100,10)
arr

array([22, 89, 49, 91, 59, 42, 92, 60, 80, 15])

In [34]:
arr.max()

92

In [35]:
arr.min()

15

In [36]:
arr.argmax()

6

In [37]:
arr.argmin()

9

In [38]:
arr.shape

(10,)

In [39]:
arr.reshape(1,10)

array([[22, 89, 49, 91, 59, 42, 92, 60, 80, 15]])

In [40]:
arr

array([22, 89, 49, 91, 59, 42, 92, 60, 80, 15])

In [41]:
arr.reshape(10,1)

array([[22],
       [89],
       [49],
       [91],
       [59],
       [42],
       [92],
       [60],
       [80],
       [15]])

# NumPy Indexing and Selection

In [23]:
arry = np.arange(0,11,2)
arry

array([ 0,  2,  4,  6,  8, 10])

In [24]:
arry[4]

8

In [25]:
arry[3:7] #excluding the stop value

array([ 6,  8, 10])

In [26]:
arry[8:10]

array([], dtype=int32)

# Broadcasting¶
NumPy arrays differ from normal Python lists because of their ability to broadcast. With lists, you can only reassign parts of a list with new parts of the same size and shape. That is, if you wanted to replace the first 5 elements in a list with a new value, you would have to pass in a new 5 element list. With NumPy arrays, you can broadcast a single value across a larger set of values:

In [27]:
arry

array([ 0,  2,  4,  6,  8, 10])

In [28]:
arry[5:9]=[12,14,56,88] #broadcasting

ValueError: could not broadcast input array from shape (4,) into shape (1,)

In [29]:
arry

array([ 0,  2,  4,  6,  8, 10])

In [30]:
arry=np.arange(0,11)
arry

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
slice_array=arry[0:6]

In [32]:
print(arry)
slice_array

[ 0  1  2  3  4  5  6  7  8  9 10]


array([0, 1, 2, 3, 4, 5])

In [33]:
slice_array[:]=100

In [34]:
arry #Now note the changes also occur in our original array!

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [35]:
#To get a copy, need to be explicit
arr_copy = arry.copy()

arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [36]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
arr_2d[2,1]

40

In [38]:
arr_2d[2]

array([35, 40, 45])

In [39]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2d[2,:]

array([35, 40, 45])

In [42]:
arr_2d[0::]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# Conditional Selection

In [62]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [64]:
bool_arr = arr>4

In [65]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [66]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

In [69]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [72]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
# This will raise a Warning on division by zero, but not an error!
# It just fills the spot with nan
arr/arr

C:\Users\Dell\AppData\Local\Temp/ipykernel_1812/205474414.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
# Also a warning (but not an error) relating to infinity
1/arr

C:\Users\Dell\AppData\Local\Temp/ipykernel_1812/616699925.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [75]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

NumPy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, which are essentially just mathematical operations that can be applied across the array.<br>Let's show some common ones:

In [76]:
# Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [77]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [78]:
# Trigonometric Functions like sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [79]:
# Taking the Natural Logarithm
np.log(arr)

C:\Users\Dell\AppData\Local\Temp/ipykernel_1812/2367246271.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## Summary Statistics on Arrays

NumPy also offers common summary statistics like <em>sum</em>, <em>mean</em> and <em>max</em>. You would call these as methods on an array.

In [80]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr.sum()

45

In [82]:
arr.mean()

4.5

In [83]:
arr.max()

9

<strong>Other summary statistics include:</strong>
<pre>
arr.min() returns 0                   minimum
arr.var() returns 8.25                variance
arr.std() returns 2.8722813232690143  standard deviation
</pre>

## Axis Logic
When working with 2-dimensional arrays (matrices) we have to consider rows and columns. This becomes very important when we get to the section on pandas. In array terms, axis 0 (zero) is the vertical axis (rows), and axis 1 is the horizonal axis (columns). These values (0,1) correspond to the order in which <tt>arr.shape</tt> values are returned.

Let's see how this affects our summary statistic calculations from above.

In [84]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [86]:
arr_2d.shape

(3, 4)

In [87]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
# THINK ABOUT WHAT THIS WILL RETURN BEFORE RUNNING THE CELL!
arr_2d.sum(axis=1)

array([10, 26, 42])

In [89]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])